### ISSUE TITLE
Strange tendon routing for `gait2354` `rect_fem_r_tendon`

### ISSUE THREAD

**Issue by tomstewart89** [MyoHub/myoconverter#39]
Hi myoconverter!

Firstly, thanks for your work on this repo, it's great to be able to simulate these models in mujoco.

While playing around with [this model](https://github.com/MyoHub/myoconverter/blob/main/models/mjc/Gait2354Simbody/gait2354_cvt1.xml) I noticed that the routing of the rectis femoris tendon was a bit strange. Specifically the tendon makes a sharp turn near the patella and its insertion doesn't seem to line up with the quadriceps tendon. Here's a screenshot to show what I mean:

![Screenshot from 2024-07-31 12-49-33](https://github.com/user-attachments/assets/96362c13-caf3-43c3-b1ec-cd34742bbbd1)

If I flip the order of the last two sites for that tendon ([like so](https://github.com/user-attachments/files/16436093/flip_sites.txt)) then I get the following routing which seems more reasonable.

![Screenshot from 2024-07-31 12-50-51](https://github.com/user-attachments/assets/d8d59c11-9b06-4bd5-b877-3fdfef42091e)

Probably this is a problem with the original model from opensim, but I figured it's worth pointing out here anyway.

Also FWIW, I'm visualizing the model using mujoco 3.1.2's `simulate` tool

**Comment by aikkala** [comment]
Hi,

This is actually not a problem with the original model from opensim, but rather a known limitation with the converter. The issue basically comes down to how we try to approximate the ConditionalPathPoints and MovingPathPoints. In this case the positions of the path points seem odd when the knee is extended, but as you flex it they make more sense. Some explanation of the issue is provided in the [documentation](https://myoconverter.readthedocs.io/en/stable/step1.html#pathpointset). All help towards fixing these issues are much appreciated!
